DATOS_ENTRENAMIENTO = [
    {"texto": "No entiendo la actividad de machine learning y necesito apoyo para comenzar", "intencion": "apoyo_academico", "sentimiento": "negativo"},
    {"texto": "Tengo dudas sobre la tarea y necesito que me expliquen el procedimiento", "intencion": "apoyo_academico", "sentimiento": "neutral"},
    {"texto": "Solicito asesoría para mejorar mi proyecto porque no sé cómo justificar el modelo", "intencion": "apoyo_academico", "sentimiento": "negativo"},
    {"texto": "Me gustaría recibir retroalimentación antes de entregar el reporte final", "intencion": "apoyo_academico", "sentimiento": "neutral"},
    {"texto": "Necesito una tutoría urgente porque reprobé el primer examen", "intencion": "apoyo_academico", "sentimiento": "negativo"},
    {"texto": "Quiero reforzar regresión lineal para entender mejor la clase", "intencion": "apoyo_academico", "sentimiento": "neutral"},
    {"texto": "El profesor explicó bien el tema y ahora entiendo mejor los datos", "intencion": "apoyo_academico", "sentimiento": "positivo"},
    {"texto": "Pido orientación para estructurar correctamente la presentación", "intencion": "apoyo_academico", "sentimiento": "neutral"},
    {"texto": "Necesito saber cómo tramitar mi constancia de estudios", "intencion": "tramite_administrativo", "sentimiento": "neutral"},
    {"texto": "No aparece mi calificación en el sistema y necesito revisión", "intencion": "tramite_administrativo", "sentimiento": "negativo"},
    {"texto": "Solicito información sobre inscripción y reinscripción del siguiente periodo", "intencion": "tramite_administrativo", "sentimiento": "neutral"},
    {"texto": "Quiero corregir mis datos personales porque están mal capturados", "intencion": "tramite_administrativo", "sentimiento": "negativo"},
    {"texto": "Necesito confirmar el horario oficial de mi grupo", "intencion": "tramite_administrativo", "sentimiento": "neutral"},
    {"texto": "El sistema no me deja descargar mi historial académico", "intencion": "tramite_administrativo", "sentimiento": "negativo"},
    {"texto": "La atención de control escolar fue rápida y amable", "intencion": "tramite_administrativo", "sentimiento": "positivo"},
    {"texto": "Solicito apoyo para validar mi comprobante de pago", "intencion": "tramite_administrativo", "sentimiento": "neutral"},
    {"texto": "Me siento muy estresado y no he podido dormir por las entregas", "intencion": "bienestar_estudiantil", "sentimiento": "negativo"},
    {"texto": "Necesito orientación porque tengo ansiedad antes de los exámenes", "intencion": "bienestar_estudiantil", "sentimiento": "negativo"},
    {"texto": "Quiero información sobre apoyo psicológico para estudiantes", "intencion": "bienestar_estudiantil", "sentimiento": "neutral"},
    {"texto": "Estoy agotado y me cuesta concentrarme en las clases", "intencion": "bienestar_estudiantil", "sentimiento": "negativo"},
    {"texto": "Me gustaría participar en actividades de integración y bienestar", "intencion": "bienestar_estudiantil", "sentimiento": "positivo"},
    {"texto": "Necesito hablar con alguien porque tengo problemas familiares", "intencion": "bienestar_estudiantil", "sentimiento": "negativo"},
    {"texto": "La campaña de salud mental me pareció útil para la comunidad", "intencion": "bienestar_estudiantil", "sentimiento": "positivo"},
    {"texto": "Solicito apoyo porque estoy perdiendo motivación para continuar", "intencion": "bienestar_estudiantil", "sentimiento": "negativo"},
    {"texto": "La plataforma no abre y no puedo subir mi archivo", "intencion": "problema_tecnico", "sentimiento": "negativo"},
    {"texto": "Tengo error al iniciar sesión en el aula virtual", "intencion": "problema_tecnico", "sentimiento": "negativo"},
    {"texto": "No carga el enlace de la videollamada de la clase", "intencion": "problema_tecnico", "sentimiento": "negativo"},
    {"texto": "El sistema se cerró cuando intenté enviar la tarea", "intencion": "problema_tecnico", "sentimiento": "negativo"},
    {"texto": "Necesito ayuda para instalar Python y ejecutar el programa", "intencion": "problema_tecnico", "sentimiento": "neutral"},
    {"texto": "La computadora del laboratorio no reconoce mi usuario", "intencion": "problema_tecnico", "sentimiento": "negativo"},
    {"texto": "El archivo se subió correctamente después de actualizar la página", "intencion": "problema_tecnico", "sentimiento": "positivo"},
    {"texto": "Solicito soporte para recuperar mi contraseña institucional", "intencion": "problema_tecnico", "sentimiento": "neutral"},
    {"texto": "La clase fue excelente y el material quedó muy claro", "intencion": "felicitacion", "sentimiento": "positivo"},
    {"texto": "Agradezco la explicación porque ayudó mucho al equipo", "intencion": "felicitacion", "sentimiento": "positivo"},
    {"texto": "El proyecto estuvo bien organizado y aprendimos bastante", "intencion": "felicitacion", "sentimiento": "positivo"},
    {"texto": "La atención recibida fue amable, rápida y profesional", "intencion": "felicitacion", "sentimiento": "positivo"},
    {"texto": "Me gustó la dinámica de participación durante la sesión", "intencion": "felicitacion", "sentimiento": "positivo"},
    {"texto": "El docente resolvió las dudas con claridad", "intencion": "felicitacion", "sentimiento": "positivo"},
    {"texto": "La actividad fue útil para comprender el procesamiento de lenguaje natural", "intencion": "felicitacion", "sentimiento": "positivo"},
    {"texto": "Reconozco el apoyo del equipo para terminar la práctica", "intencion": "felicitacion", "sentimiento": "positivo"},
    {"texto": "El servicio fue lento y nadie respondió mi solicitud", "intencion": "queja_servicio", "sentimiento": "negativo"},
    {"texto": "Me molesta que cambien las indicaciones sin avisar", "intencion": "queja_servicio", "sentimiento": "negativo"},
    {"texto": "La respuesta que recibí fue confusa y poco útil", "intencion": "queja_servicio", "sentimiento": "negativo"},
    {"texto": "No estoy satisfecho con la atención porque tardaron demasiado", "intencion": "queja_servicio", "sentimiento": "negativo"},
    {"texto": "El aula estaba cerrada y nadie explicó el cambio de salón", "intencion": "queja_servicio", "sentimiento": "negativo"},
    {"texto": "La información publicada no coincide con lo que dijeron en clase", "intencion": "queja_servicio", "sentimiento": "negativo"},
    {"texto": "Hubo desorganización durante la entrega del proyecto", "intencion": "queja_servicio", "sentimiento": "negativo"},
    {"texto": "El trámite se retrasó y eso afectó mi inscripción", "intencion": "queja_servicio", "sentimiento": "negativo"},
    {"texto": "Quisiera conocer la fecha de la próxima entrega", "intencion": "consulta_general", "sentimiento": "neutral"},
    {"texto": "¿Dónde puedo consultar el calendario académico?", "intencion": "consulta_general", "sentimiento": "neutral"},
    {"texto": "Necesito saber si la presentación será individual o en equipo", "intencion": "consulta_general", "sentimiento": "neutral"},
    {"texto": "Quiero confirmar el formato del archivo que se debe entregar", "intencion": "consulta_general", "sentimiento": "neutral"},
    {"texto": "Me pueden indicar el salón asignado para mañana", "intencion": "consulta_general", "sentimiento": "neutral"},
    {"texto": "Tengo una pregunta sobre la duración del pitch", "intencion": "consulta_general", "sentimiento": "neutral"},
    {"texto": "Solicito la liga del material de apoyo", "intencion": "consulta_general", "sentimiento": "neutral"},
    {"texto": "Quisiera saber quién revisará el reporte final", "intencion": "consulta_general", "sentimiento": "neutral"}
]
